[refactor]: sh-script templates

diff --git a/code/sh-mode/polyglot/_help b/code/sh-mode/polyglot/_help
--- a/code/sh-mode/polyglot/_help
+++ b/code/sh-mode/polyglot/_help
@@ -12,9 +12,19 @@ set -o pipefail
 
 # shellcheck disable=SC1091
 source "$POLY_SRC/lib/lib-util.bash"
-if [[ -e "$POLYGLOT_ROOT/.tasks/task-util.bash" ]]; then
-    source "$POLYGLOT_ROOT/.tasks/task-util.bash"
-fi
+# shellcheck disable=SC1091
+[[ -e "$POLYGLOT_ROOT/.tasks/task-util.bash" ]] && source "$POLYGLOT_ROOT/.tasks/task-util.bash"
+
+HELP_TEXT="
+usage: polyglot task {taskname} [args ...] [-h]
+
+positional arguments:
+args          :
+
+options:
+-h, --help    : show this help message and exit
+
+"
 
 function print-help () {
     # test args, if the last one is -h or --help
@@ -27,32 +37,17 @@ function print-help () {
     #        ;;
         *) return ;;
     esac
-    echo -e "
-usage: polyglot task {taskname} [args ...] [-h]
-
-positional arguments:
-args          :
-
-options:
--h, --help    : show this help message and exit
-
-
-"
-    exit "${PRINTED_HELP:-2}"
+    echo -e "$HELP_TEXT"
+    exit "$PRINTED_HELP"
 }
 
 function check-environment () {
     subhead "Checking Environment"
     has_failed=0
 
-    # if [[ -z "${BIBLIO_LIB:-}" ]]; then
-    #     has_failed=1
-    #     echo -e "!-- No BIBLIO_LIB has been defined"
-    # fi
+    # [[ -z "${BIBLIO_LIB:-}" ]] || { has_failed=1; echo -e "!-- No BIBLIO_LIB has been defined"; }
 
-    if [[ "$has_failed" -gt 0 ]]; then
-        fail "Missing EnvVars"
-    fi
+    [[ "$has_failed" = 0 ]] || fail "Missing EnvVars"
 }
 
 print-help "$@"
